import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { APPLE_TOUCH_ICON, OG_IMAGE } from './og'

// These images are generated by scripts/images.ts and committed, so nothing at
// build time or request time checks them. What can still be checked from the
// bytes is checked here: that they exist, that they are the format and the size
// the head claims, and that the .ico is a container a browser can actually
// open. A card of the wrong size is cropped and a broken one shows as an empty
// panel — neither fails anything, which is why they are worth a test.

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

function read(path: string): Buffer {
  return readFileSync(new URL(`../../public${path}`, import.meta.url))
}

/** Width and height out of a PNG's IHDR, which is always the first chunk. */
function pngSize(bytes: Buffer): { width: number; height: number } {
  expect(bytes.subarray(0, 8)).toEqual(PNG_SIGNATURE)
  expect(bytes.subarray(12, 16).toString('latin1')).toBe('IHDR')
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) }
}

describe('the social card', () => {
  it('is a PNG at the size the head advertises', () => {
    expect(pngSize(read(OG_IMAGE.path))).toEqual({
      width: OG_IMAGE.width,
      height: OG_IMAGE.height,
    })
  })
})

describe('the apple touch icon', () => {
  it('is a square PNG at the size iOS asks for', () => {
    expect(pngSize(read(APPLE_TOUCH_ICON.path))).toEqual({
      width: APPLE_TOUCH_ICON.size,
      height: APPLE_TOUCH_ICON.size,
    })
  })
})

describe('favicon.ico', () => {
  const bytes = read('/favicon.ico')

  it('is an icon directory, not a PNG someone renamed', () => {
    expect(bytes.readUInt16LE(0)).toBe(0) // reserved
    expect(bytes.readUInt16LE(2)).toBe(1) // 1 = icon
    expect(bytes.readUInt16LE(4)).toBeGreaterThan(0)
  })

  it('holds PNGs at 16 and 32, each where its entry says it is', () => {
    const count = bytes.readUInt16LE(4)
    const entries = Array.from({ length: count }, (_, i) => {
      const at = 6 + 16 * i
      return {
        size: bytes.readUInt8(at) === 0 ? 256 : bytes.readUInt8(at),
        length: bytes.readUInt32LE(at + 8),
        offset: bytes.readUInt32LE(at + 12),
      }
    })

    expect(entries.map((e) => e.size)).toEqual([16, 32])
    for (const entry of entries) {
      const image = bytes.subarray(entry.offset, entry.offset + entry.length)
      expect(image.length).toBe(entry.length)
      expect(pngSize(image)).toEqual({ width: entry.size, height: entry.size })
    }
  })
})
